import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { FC } from "react";

export const metadata: Metadata = {
  title: "Google Flights - Find cheap flight options and track prices.",
  description: "Generated by create next app",
};

export default function RootLayout:FC({children}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
